/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AAlogicoPbinaryExpr extends PPbinaryExpr
{
    private PPbinaryLogicoExp _pbinaryLogicoExp_;

    public AAlogicoPbinaryExpr()
    {
        // Constructor
    }

    public AAlogicoPbinaryExpr(
        @SuppressWarnings("hiding") PPbinaryLogicoExp _pbinaryLogicoExp_)
    {
        // Constructor
        setPbinaryLogicoExp(_pbinaryLogicoExp_);

    }

    @Override
    public Object clone()
    {
        return new AAlogicoPbinaryExpr(
            cloneNode(this._pbinaryLogicoExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAlogicoPbinaryExpr(this);
    }

    public PPbinaryLogicoExp getPbinaryLogicoExp()
    {
        return this._pbinaryLogicoExp_;
    }

    public void setPbinaryLogicoExp(PPbinaryLogicoExp node)
    {
        if(this._pbinaryLogicoExp_ != null)
        {
            this._pbinaryLogicoExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pbinaryLogicoExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pbinaryLogicoExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pbinaryLogicoExp_ == child)
        {
            this._pbinaryLogicoExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pbinaryLogicoExp_ == oldChild)
        {
            setPbinaryLogicoExp((PPbinaryLogicoExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
