/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AArelacionalPbinaryExpr extends PPbinaryExpr
{
    private PPbinaryRelExp _pbinaryRelExp_;

    public AArelacionalPbinaryExpr()
    {
        // Constructor
    }

    public AArelacionalPbinaryExpr(
        @SuppressWarnings("hiding") PPbinaryRelExp _pbinaryRelExp_)
    {
        // Constructor
        setPbinaryRelExp(_pbinaryRelExp_);

    }

    @Override
    public Object clone()
    {
        return new AArelacionalPbinaryExpr(
            cloneNode(this._pbinaryRelExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArelacionalPbinaryExpr(this);
    }

    public PPbinaryRelExp getPbinaryRelExp()
    {
        return this._pbinaryRelExp_;
    }

    public void setPbinaryRelExp(PPbinaryRelExp node)
    {
        if(this._pbinaryRelExp_ != null)
        {
            this._pbinaryRelExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pbinaryRelExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pbinaryRelExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pbinaryRelExp_ == child)
        {
            this._pbinaryRelExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pbinaryRelExp_ == oldChild)
        {
            setPbinaryRelExp((PPbinaryRelExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
