/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ABlocoPstatement extends PPstatement
{
    private PPblock _pblock_;

    public ABlocoPstatement()
    {
        // Constructor
    }

    public ABlocoPstatement(
        @SuppressWarnings("hiding") PPblock _pblock_)
    {
        // Constructor
        setPblock(_pblock_);

    }

    @Override
    public Object clone()
    {
        return new ABlocoPstatement(
            cloneNode(this._pblock_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABlocoPstatement(this);
    }

    public PPblock getPblock()
    {
        return this._pblock_;
    }

    public void setPblock(PPblock node)
    {
        if(this._pblock_ != null)
        {
            this._pblock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pblock_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pblock_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pblock_ == child)
        {
            this._pblock_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pblock_ == oldChild)
        {
            setPblock((PPblock) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
