/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AClusuraForPforStmtOpc extends PPforStmtOpc
{
    private PPforClause _pforClause_;

    public AClusuraForPforStmtOpc()
    {
        // Constructor
    }

    public AClusuraForPforStmtOpc(
        @SuppressWarnings("hiding") PPforClause _pforClause_)
    {
        // Constructor
        setPforClause(_pforClause_);

    }

    @Override
    public Object clone()
    {
        return new AClusuraForPforStmtOpc(
            cloneNode(this._pforClause_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClusuraForPforStmtOpc(this);
    }

    public PPforClause getPforClause()
    {
        return this._pforClause_;
    }

    public void setPforClause(PPforClause node)
    {
        if(this._pforClause_ != null)
        {
            this._pforClause_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pforClause_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pforClause_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pforClause_ == child)
        {
            this._pforClause_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pforClause_ == oldChild)
        {
            setPforClause((PPforClause) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
