/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ACondicaoPforStmtOpc extends PPforStmtOpc
{
    private PPcondition _pcondition_;

    public ACondicaoPforStmtOpc()
    {
        // Constructor
    }

    public ACondicaoPforStmtOpc(
        @SuppressWarnings("hiding") PPcondition _pcondition_)
    {
        // Constructor
        setPcondition(_pcondition_);

    }

    @Override
    public Object clone()
    {
        return new ACondicaoPforStmtOpc(
            cloneNode(this._pcondition_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACondicaoPforStmtOpc(this);
    }

    public PPcondition getPcondition()
    {
        return this._pcondition_;
    }

    public void setPcondition(PPcondition node)
    {
        if(this._pcondition_ != null)
        {
            this._pcondition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pcondition_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pcondition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pcondition_ == child)
        {
            this._pcondition_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pcondition_ == oldChild)
        {
            setPcondition((PPcondition) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
