/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaGrupoPvarDeclAgrup extends PPvarDeclAgrup
{
    private PPvarSpec _pvarSpec_;

    public ADeclaGrupoPvarDeclAgrup()
    {
        // Constructor
    }

    public ADeclaGrupoPvarDeclAgrup(
        @SuppressWarnings("hiding") PPvarSpec _pvarSpec_)
    {
        // Constructor
        setPvarSpec(_pvarSpec_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaGrupoPvarDeclAgrup(
            cloneNode(this._pvarSpec_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaGrupoPvarDeclAgrup(this);
    }

    public PPvarSpec getPvarSpec()
    {
        return this._pvarSpec_;
    }

    public void setPvarSpec(PPvarSpec node)
    {
        if(this._pvarSpec_ != null)
        {
            this._pvarSpec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pvarSpec_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pvarSpec_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pvarSpec_ == child)
        {
            this._pvarSpec_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pvarSpec_ == oldChild)
        {
            setPvarSpec((PPvarSpec) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
