/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ADsPbinaryLogicoFactor extends PPbinaryLogicoFactor
{
    private PPbinaryLogicoFactorNot _pbinaryLogicoFactorNot_;

    public ADsPbinaryLogicoFactor()
    {
        // Constructor
    }

    public ADsPbinaryLogicoFactor(
        @SuppressWarnings("hiding") PPbinaryLogicoFactorNot _pbinaryLogicoFactorNot_)
    {
        // Constructor
        setPbinaryLogicoFactorNot(_pbinaryLogicoFactorNot_);

    }

    @Override
    public Object clone()
    {
        return new ADsPbinaryLogicoFactor(
            cloneNode(this._pbinaryLogicoFactorNot_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADsPbinaryLogicoFactor(this);
    }

    public PPbinaryLogicoFactorNot getPbinaryLogicoFactorNot()
    {
        return this._pbinaryLogicoFactorNot_;
    }

    public void setPbinaryLogicoFactorNot(PPbinaryLogicoFactorNot node)
    {
        if(this._pbinaryLogicoFactorNot_ != null)
        {
            this._pbinaryLogicoFactorNot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pbinaryLogicoFactorNot_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pbinaryLogicoFactorNot_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pbinaryLogicoFactorNot_ == child)
        {
            this._pbinaryLogicoFactorNot_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pbinaryLogicoFactorNot_ == oldChild)
        {
            setPbinaryLogicoFactorNot((PPbinaryLogicoFactorNot) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
