/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AElementoLoopPelementLit extends PPelementLit
{
    private PPelementLitLoop _pelementLitLoop_;

    public AElementoLoopPelementLit()
    {
        // Constructor
    }

    public AElementoLoopPelementLit(
        @SuppressWarnings("hiding") PPelementLitLoop _pelementLitLoop_)
    {
        // Constructor
        setPelementLitLoop(_pelementLitLoop_);

    }

    @Override
    public Object clone()
    {
        return new AElementoLoopPelementLit(
            cloneNode(this._pelementLitLoop_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElementoLoopPelementLit(this);
    }

    public PPelementLitLoop getPelementLitLoop()
    {
        return this._pelementLitLoop_;
    }

    public void setPelementLitLoop(PPelementLitLoop node)
    {
        if(this._pelementLitLoop_ != null)
        {
            this._pelementLitLoop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pelementLitLoop_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pelementLitLoop_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pelementLitLoop_ == child)
        {
            this._pelementLitLoop_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pelementLitLoop_ == oldChild)
        {
            setPelementLitLoop((PPelementLitLoop) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
