/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AIdentificadorListaPrangeClauseOpc extends PPrangeClauseOpc
{
    private PPidentifierList _pidentifierList_;
    private TTdeclaracaoAtribuicao _tdeclaracaoAtribuicao_;

    public AIdentificadorListaPrangeClauseOpc()
    {
        // Constructor
    }

    public AIdentificadorListaPrangeClauseOpc(
        @SuppressWarnings("hiding") PPidentifierList _pidentifierList_,
        @SuppressWarnings("hiding") TTdeclaracaoAtribuicao _tdeclaracaoAtribuicao_)
    {
        // Constructor
        setPidentifierList(_pidentifierList_);

        setTdeclaracaoAtribuicao(_tdeclaracaoAtribuicao_);

    }

    @Override
    public Object clone()
    {
        return new AIdentificadorListaPrangeClauseOpc(
            cloneNode(this._pidentifierList_),
            cloneNode(this._tdeclaracaoAtribuicao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdentificadorListaPrangeClauseOpc(this);
    }

    public PPidentifierList getPidentifierList()
    {
        return this._pidentifierList_;
    }

    public void setPidentifierList(PPidentifierList node)
    {
        if(this._pidentifierList_ != null)
        {
            this._pidentifierList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pidentifierList_ = node;
    }

    public TTdeclaracaoAtribuicao getTdeclaracaoAtribuicao()
    {
        return this._tdeclaracaoAtribuicao_;
    }

    public void setTdeclaracaoAtribuicao(TTdeclaracaoAtribuicao node)
    {
        if(this._tdeclaracaoAtribuicao_ != null)
        {
            this._tdeclaracaoAtribuicao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tdeclaracaoAtribuicao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pidentifierList_)
            + toString(this._tdeclaracaoAtribuicao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pidentifierList_ == child)
        {
            this._pidentifierList_ = null;
            return;
        }

        if(this._tdeclaracaoAtribuicao_ == child)
        {
            this._tdeclaracaoAtribuicao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pidentifierList_ == oldChild)
        {
            setPidentifierList((PPidentifierList) newChild);
            return;
        }

        if(this._tdeclaracaoAtribuicao_ == oldChild)
        {
            setTdeclaracaoAtribuicao((TTdeclaracaoAtribuicao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
