/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AIfPelseAgrup extends PPelseAgrup
{
    private PPifStmt _pifStmt_;

    public AIfPelseAgrup()
    {
        // Constructor
    }

    public AIfPelseAgrup(
        @SuppressWarnings("hiding") PPifStmt _pifStmt_)
    {
        // Constructor
        setPifStmt(_pifStmt_);

    }

    @Override
    public Object clone()
    {
        return new AIfPelseAgrup(
            cloneNode(this._pifStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfPelseAgrup(this);
    }

    public PPifStmt getPifStmt()
    {
        return this._pifStmt_;
    }

    public void setPifStmt(PPifStmt node)
    {
        if(this._pifStmt_ != null)
        {
            this._pifStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pifStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pifStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pifStmt_ == child)
        {
            this._pifStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pifStmt_ == oldChild)
        {
            setPifStmt((PPifStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
