/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AListaExpressaoPrangeClauseOpc extends PPrangeClauseOpc
{
    private PPexpressionList _pexpressionList_;
    private TTigual _tigual_;

    public AListaExpressaoPrangeClauseOpc()
    {
        // Constructor
    }

    public AListaExpressaoPrangeClauseOpc(
        @SuppressWarnings("hiding") PPexpressionList _pexpressionList_,
        @SuppressWarnings("hiding") TTigual _tigual_)
    {
        // Constructor
        setPexpressionList(_pexpressionList_);

        setTigual(_tigual_);

    }

    @Override
    public Object clone()
    {
        return new AListaExpressaoPrangeClauseOpc(
            cloneNode(this._pexpressionList_),
            cloneNode(this._tigual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaExpressaoPrangeClauseOpc(this);
    }

    public PPexpressionList getPexpressionList()
    {
        return this._pexpressionList_;
    }

    public void setPexpressionList(PPexpressionList node)
    {
        if(this._pexpressionList_ != null)
        {
            this._pexpressionList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pexpressionList_ = node;
    }

    public TTigual getTigual()
    {
        return this._tigual_;
    }

    public void setTigual(TTigual node)
    {
        if(this._tigual_ != null)
        {
            this._tigual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tigual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pexpressionList_)
            + toString(this._tigual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pexpressionList_ == child)
        {
            this._pexpressionList_ = null;
            return;
        }

        if(this._tigual_ == child)
        {
            this._tigual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pexpressionList_ == oldChild)
        {
            setPexpressionList((PPexpressionList) newChild);
            return;
        }

        if(this._tigual_ == oldChild)
        {
            setTigual((TTigual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
