/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ANmeCampoPkey extends PPkey
{
    private PPfieldName _pfieldName_;

    public ANmeCampoPkey()
    {
        // Constructor
    }

    public ANmeCampoPkey(
        @SuppressWarnings("hiding") PPfieldName _pfieldName_)
    {
        // Constructor
        setPfieldName(_pfieldName_);

    }

    @Override
    public Object clone()
    {
        return new ANmeCampoPkey(
            cloneNode(this._pfieldName_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANmeCampoPkey(this);
    }

    public PPfieldName getPfieldName()
    {
        return this._pfieldName_;
    }

    public void setPfieldName(PPfieldName node)
    {
        if(this._pfieldName_ != null)
        {
            this._pfieldName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pfieldName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pfieldName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pfieldName_ == child)
        {
            this._pfieldName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pfieldName_ == oldChild)
        {
            setPfieldName((PPfieldName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
