/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AParametrosPresult extends PPresult
{
    private PPparameters _pparameters_;

    public AParametrosPresult()
    {
        // Constructor
    }

    public AParametrosPresult(
        @SuppressWarnings("hiding") PPparameters _pparameters_)
    {
        // Constructor
        setPparameters(_pparameters_);

    }

    @Override
    public Object clone()
    {
        return new AParametrosPresult(
            cloneNode(this._pparameters_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParametrosPresult(this);
    }

    public PPparameters getPparameters()
    {
        return this._pparameters_;
    }

    public void setPparameters(PPparameters node)
    {
        if(this._pparameters_ != null)
        {
            this._pparameters_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pparameters_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pparameters_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pparameters_ == child)
        {
            this._pparameters_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pparameters_ == oldChild)
        {
            setPparameters((PPparameters) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
