/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APargumentsCorpo extends PPargumentsCorpo
{
    private PPargumentsCorpoAgrup _pargumentsCorpoAgrup_;
    private TTellipsis _tellipsis_;
    private TTvirgula _tvirgula_;

    public APargumentsCorpo()
    {
        // Constructor
    }

    public APargumentsCorpo(
        @SuppressWarnings("hiding") PPargumentsCorpoAgrup _pargumentsCorpoAgrup_,
        @SuppressWarnings("hiding") TTellipsis _tellipsis_,
        @SuppressWarnings("hiding") TTvirgula _tvirgula_)
    {
        // Constructor
        setPargumentsCorpoAgrup(_pargumentsCorpoAgrup_);

        setTellipsis(_tellipsis_);

        setTvirgula(_tvirgula_);

    }

    @Override
    public Object clone()
    {
        return new APargumentsCorpo(
            cloneNode(this._pargumentsCorpoAgrup_),
            cloneNode(this._tellipsis_),
            cloneNode(this._tvirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPargumentsCorpo(this);
    }

    public PPargumentsCorpoAgrup getPargumentsCorpoAgrup()
    {
        return this._pargumentsCorpoAgrup_;
    }

    public void setPargumentsCorpoAgrup(PPargumentsCorpoAgrup node)
    {
        if(this._pargumentsCorpoAgrup_ != null)
        {
            this._pargumentsCorpoAgrup_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pargumentsCorpoAgrup_ = node;
    }

    public TTellipsis getTellipsis()
    {
        return this._tellipsis_;
    }

    public void setTellipsis(TTellipsis node)
    {
        if(this._tellipsis_ != null)
        {
            this._tellipsis_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tellipsis_ = node;
    }

    public TTvirgula getTvirgula()
    {
        return this._tvirgula_;
    }

    public void setTvirgula(TTvirgula node)
    {
        if(this._tvirgula_ != null)
        {
            this._tvirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tvirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pargumentsCorpoAgrup_)
            + toString(this._tellipsis_)
            + toString(this._tvirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pargumentsCorpoAgrup_ == child)
        {
            this._pargumentsCorpoAgrup_ = null;
            return;
        }

        if(this._tellipsis_ == child)
        {
            this._tellipsis_ = null;
            return;
        }

        if(this._tvirgula_ == child)
        {
            this._tvirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pargumentsCorpoAgrup_ == oldChild)
        {
            setPargumentsCorpoAgrup((PPargumentsCorpoAgrup) newChild);
            return;
        }

        if(this._tellipsis_ == oldChild)
        {
            setTellipsis((TTellipsis) newChild);
            return;
        }

        if(this._tvirgula_ == oldChild)
        {
            setTvirgula((TTvirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
