/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APbinaryRelExp extends PPbinaryRelExp
{
    private PPbinaryRelExp _pbinaryRelExp_;
    private PPrelOp _prelOp_;
    private PPbinaryRelTermo _pbinaryRelTermo_;

    public APbinaryRelExp()
    {
        // Constructor
    }

    public APbinaryRelExp(
        @SuppressWarnings("hiding") PPbinaryRelExp _pbinaryRelExp_,
        @SuppressWarnings("hiding") PPrelOp _prelOp_,
        @SuppressWarnings("hiding") PPbinaryRelTermo _pbinaryRelTermo_)
    {
        // Constructor
        setPbinaryRelExp(_pbinaryRelExp_);

        setPrelOp(_prelOp_);

        setPbinaryRelTermo(_pbinaryRelTermo_);

    }

    @Override
    public Object clone()
    {
        return new APbinaryRelExp(
            cloneNode(this._pbinaryRelExp_),
            cloneNode(this._prelOp_),
            cloneNode(this._pbinaryRelTermo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPbinaryRelExp(this);
    }

    public PPbinaryRelExp getPbinaryRelExp()
    {
        return this._pbinaryRelExp_;
    }

    public void setPbinaryRelExp(PPbinaryRelExp node)
    {
        if(this._pbinaryRelExp_ != null)
        {
            this._pbinaryRelExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pbinaryRelExp_ = node;
    }

    public PPrelOp getPrelOp()
    {
        return this._prelOp_;
    }

    public void setPrelOp(PPrelOp node)
    {
        if(this._prelOp_ != null)
        {
            this._prelOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._prelOp_ = node;
    }

    public PPbinaryRelTermo getPbinaryRelTermo()
    {
        return this._pbinaryRelTermo_;
    }

    public void setPbinaryRelTermo(PPbinaryRelTermo node)
    {
        if(this._pbinaryRelTermo_ != null)
        {
            this._pbinaryRelTermo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pbinaryRelTermo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pbinaryRelExp_)
            + toString(this._prelOp_)
            + toString(this._pbinaryRelTermo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pbinaryRelExp_ == child)
        {
            this._pbinaryRelExp_ = null;
            return;
        }

        if(this._prelOp_ == child)
        {
            this._prelOp_ = null;
            return;
        }

        if(this._pbinaryRelTermo_ == child)
        {
            this._pbinaryRelTermo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pbinaryRelExp_ == oldChild)
        {
            setPbinaryRelExp((PPbinaryRelExp) newChild);
            return;
        }

        if(this._prelOp_ == oldChild)
        {
            setPrelOp((PPrelOp) newChild);
            return;
        }

        if(this._pbinaryRelTermo_ == oldChild)
        {
            setPbinaryRelTermo((PPbinaryRelTermo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
