/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APbinaryLogicoExp extends PPbinaryLogicoExp
{
    private PPbinaryLogicoExp _pbinaryLogicoExp_;
    private TTorLogico _torLogico_;
    private PPbinaryLogicoFactor _pbinaryLogicoFactor_;

    public APbinaryLogicoExp()
    {
        // Constructor
    }

    public APbinaryLogicoExp(
        @SuppressWarnings("hiding") PPbinaryLogicoExp _pbinaryLogicoExp_,
        @SuppressWarnings("hiding") TTorLogico _torLogico_,
        @SuppressWarnings("hiding") PPbinaryLogicoFactor _pbinaryLogicoFactor_)
    {
        // Constructor
        setPbinaryLogicoExp(_pbinaryLogicoExp_);

        setTorLogico(_torLogico_);

        setPbinaryLogicoFactor(_pbinaryLogicoFactor_);

    }

    @Override
    public Object clone()
    {
        return new APbinaryLogicoExp(
            cloneNode(this._pbinaryLogicoExp_),
            cloneNode(this._torLogico_),
            cloneNode(this._pbinaryLogicoFactor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPbinaryLogicoExp(this);
    }

    public PPbinaryLogicoExp getPbinaryLogicoExp()
    {
        return this._pbinaryLogicoExp_;
    }

    public void setPbinaryLogicoExp(PPbinaryLogicoExp node)
    {
        if(this._pbinaryLogicoExp_ != null)
        {
            this._pbinaryLogicoExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pbinaryLogicoExp_ = node;
    }

    public TTorLogico getTorLogico()
    {
        return this._torLogico_;
    }

    public void setTorLogico(TTorLogico node)
    {
        if(this._torLogico_ != null)
        {
            this._torLogico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._torLogico_ = node;
    }

    public PPbinaryLogicoFactor getPbinaryLogicoFactor()
    {
        return this._pbinaryLogicoFactor_;
    }

    public void setPbinaryLogicoFactor(PPbinaryLogicoFactor node)
    {
        if(this._pbinaryLogicoFactor_ != null)
        {
            this._pbinaryLogicoFactor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pbinaryLogicoFactor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pbinaryLogicoExp_)
            + toString(this._torLogico_)
            + toString(this._pbinaryLogicoFactor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pbinaryLogicoExp_ == child)
        {
            this._pbinaryLogicoExp_ = null;
            return;
        }

        if(this._torLogico_ == child)
        {
            this._torLogico_ = null;
            return;
        }

        if(this._pbinaryLogicoFactor_ == child)
        {
            this._pbinaryLogicoFactor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pbinaryLogicoExp_ == oldChild)
        {
            setPbinaryLogicoExp((PPbinaryLogicoExp) newChild);
            return;
        }

        if(this._torLogico_ == oldChild)
        {
            setTorLogico((TTorLogico) newChild);
            return;
        }

        if(this._pbinaryLogicoFactor_ == oldChild)
        {
            setPbinaryLogicoFactor((PPbinaryLogicoFactor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
