/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APconstDeclPdeclaration extends PPdeclaration
{
    private PPconstDecl _pconstDecl_;

    public APconstDeclPdeclaration()
    {
        // Constructor
    }

    public APconstDeclPdeclaration(
        @SuppressWarnings("hiding") PPconstDecl _pconstDecl_)
    {
        // Constructor
        setPconstDecl(_pconstDecl_);

    }

    @Override
    public Object clone()
    {
        return new APconstDeclPdeclaration(
            cloneNode(this._pconstDecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPconstDeclPdeclaration(this);
    }

    public PPconstDecl getPconstDecl()
    {
        return this._pconstDecl_;
    }

    public void setPconstDecl(PPconstDecl node)
    {
        if(this._pconstDecl_ != null)
        {
            this._pconstDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pconstDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pconstDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pconstDecl_ == child)
        {
            this._pconstDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pconstDecl_ == oldChild)
        {
            setPconstDecl((PPconstDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
