/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APconstSpec2PconstSpec extends PPconstSpec
{
    private PPconstSpec2 _pconstSpec2_;

    public APconstSpec2PconstSpec()
    {
        // Constructor
    }

    public APconstSpec2PconstSpec(
        @SuppressWarnings("hiding") PPconstSpec2 _pconstSpec2_)
    {
        // Constructor
        setPconstSpec2(_pconstSpec2_);

    }

    @Override
    public Object clone()
    {
        return new APconstSpec2PconstSpec(
            cloneNode(this._pconstSpec2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPconstSpec2PconstSpec(this);
    }

    public PPconstSpec2 getPconstSpec2()
    {
        return this._pconstSpec2_;
    }

    public void setPconstSpec2(PPconstSpec2 node)
    {
        if(this._pconstSpec2_ != null)
        {
            this._pconstSpec2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pconstSpec2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pconstSpec2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pconstSpec2_ == child)
        {
            this._pconstSpec2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pconstSpec2_ == oldChild)
        {
            setPconstSpec2((PPconstSpec2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
