/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APconstDeclConteudo extends PPconstDeclConteudo
{
    private PPconstSpecIdent _pconstSpecIdent_;
    private TTdelimitador _tdelimitador_;

    public APconstDeclConteudo()
    {
        // Constructor
    }

    public APconstDeclConteudo(
        @SuppressWarnings("hiding") PPconstSpecIdent _pconstSpecIdent_,
        @SuppressWarnings("hiding") TTdelimitador _tdelimitador_)
    {
        // Constructor
        setPconstSpecIdent(_pconstSpecIdent_);

        setTdelimitador(_tdelimitador_);

    }

    @Override
    public Object clone()
    {
        return new APconstDeclConteudo(
            cloneNode(this._pconstSpecIdent_),
            cloneNode(this._tdelimitador_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPconstDeclConteudo(this);
    }

    public PPconstSpecIdent getPconstSpecIdent()
    {
        return this._pconstSpecIdent_;
    }

    public void setPconstSpecIdent(PPconstSpecIdent node)
    {
        if(this._pconstSpecIdent_ != null)
        {
            this._pconstSpecIdent_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pconstSpecIdent_ = node;
    }

    public TTdelimitador getTdelimitador()
    {
        return this._tdelimitador_;
    }

    public void setTdelimitador(TTdelimitador node)
    {
        if(this._tdelimitador_ != null)
        {
            this._tdelimitador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tdelimitador_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pconstSpecIdent_)
            + toString(this._tdelimitador_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pconstSpecIdent_ == child)
        {
            this._pconstSpecIdent_ = null;
            return;
        }

        if(this._tdelimitador_ == child)
        {
            this._tdelimitador_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pconstSpecIdent_ == oldChild)
        {
            setPconstSpecIdent((PPconstSpecIdent) newChild);
            return;
        }

        if(this._tdelimitador_ == oldChild)
        {
            setTdelimitador((TTdelimitador) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
