/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APcompositeLit extends PPcompositeLit
{
    private PPliteralType _pliteralType_;
    private PPliteralValue _pliteralValue_;

    public APcompositeLit()
    {
        // Constructor
    }

    public APcompositeLit(
        @SuppressWarnings("hiding") PPliteralType _pliteralType_,
        @SuppressWarnings("hiding") PPliteralValue _pliteralValue_)
    {
        // Constructor
        setPliteralType(_pliteralType_);

        setPliteralValue(_pliteralValue_);

    }

    @Override
    public Object clone()
    {
        return new APcompositeLit(
            cloneNode(this._pliteralType_),
            cloneNode(this._pliteralValue_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPcompositeLit(this);
    }

    public PPliteralType getPliteralType()
    {
        return this._pliteralType_;
    }

    public void setPliteralType(PPliteralType node)
    {
        if(this._pliteralType_ != null)
        {
            this._pliteralType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pliteralType_ = node;
    }

    public PPliteralValue getPliteralValue()
    {
        return this._pliteralValue_;
    }

    public void setPliteralValue(PPliteralValue node)
    {
        if(this._pliteralValue_ != null)
        {
            this._pliteralValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pliteralValue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pliteralType_)
            + toString(this._pliteralValue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pliteralType_ == child)
        {
            this._pliteralType_ = null;
            return;
        }

        if(this._pliteralValue_ == child)
        {
            this._pliteralValue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pliteralType_ == oldChild)
        {
            setPliteralType((PPliteralType) newChild);
            return;
        }

        if(this._pliteralValue_ == oldChild)
        {
            setPliteralValue((PPliteralValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
