/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APconstSpecIdentPconstDecl2 extends PPconstDecl2
{
    private PPconstSpecIdent _pconstSpecIdent_;

    public APconstSpecIdentPconstDecl2()
    {
        // Constructor
    }

    public APconstSpecIdentPconstDecl2(
        @SuppressWarnings("hiding") PPconstSpecIdent _pconstSpecIdent_)
    {
        // Constructor
        setPconstSpecIdent(_pconstSpecIdent_);

    }

    @Override
    public Object clone()
    {
        return new APconstSpecIdentPconstDecl2(
            cloneNode(this._pconstSpecIdent_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPconstSpecIdentPconstDecl2(this);
    }

    public PPconstSpecIdent getPconstSpecIdent()
    {
        return this._pconstSpecIdent_;
    }

    public void setPconstSpecIdent(PPconstSpecIdent node)
    {
        if(this._pconstSpecIdent_ != null)
        {
            this._pconstSpecIdent_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pconstSpecIdent_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pconstSpecIdent_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pconstSpecIdent_ == child)
        {
            this._pconstSpecIdent_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pconstSpecIdent_ == oldChild)
        {
            setPconstSpecIdent((PPconstSpecIdent) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
