/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APelementLit extends PPelementLit
{
    private PPkeyedElement _pkeyedElement_;

    public APelementLit()
    {
        // Constructor
    }

    public APelementLit(
        @SuppressWarnings("hiding") PPkeyedElement _pkeyedElement_)
    {
        // Constructor
        setPkeyedElement(_pkeyedElement_);

    }

    @Override
    public Object clone()
    {
        return new APelementLit(
            cloneNode(this._pkeyedElement_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPelementLit(this);
    }

    public PPkeyedElement getPkeyedElement()
    {
        return this._pkeyedElement_;
    }

    public void setPkeyedElement(PPkeyedElement node)
    {
        if(this._pkeyedElement_ != null)
        {
            this._pkeyedElement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pkeyedElement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pkeyedElement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pkeyedElement_ == child)
        {
            this._pkeyedElement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pkeyedElement_ == oldChild)
        {
            setPkeyedElement((PPkeyedElement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
