/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APelementType extends PPelementType
{
    private PPtype _ptype_;

    public APelementType()
    {
        // Constructor
    }

    public APelementType(
        @SuppressWarnings("hiding") PPtype _ptype_)
    {
        // Constructor
        setPtype(_ptype_);

    }

    @Override
    public Object clone()
    {
        return new APelementType(
            cloneNode(this._ptype_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPelementType(this);
    }

    public PPtype getPtype()
    {
        return this._ptype_;
    }

    public void setPtype(PPtype node)
    {
        if(this._ptype_ != null)
        {
            this._ptype_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ptype_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ptype_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ptype_ == child)
        {
            this._ptype_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ptype_ == oldChild)
        {
            setPtype((PPtype) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
