/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APexpressionListLoop extends PPexpressionListLoop
{
    private TTvirgula _tvirgula_;
    private PPexpression _pexpression_;

    public APexpressionListLoop()
    {
        // Constructor
    }

    public APexpressionListLoop(
        @SuppressWarnings("hiding") TTvirgula _tvirgula_,
        @SuppressWarnings("hiding") PPexpression _pexpression_)
    {
        // Constructor
        setTvirgula(_tvirgula_);

        setPexpression(_pexpression_);

    }

    @Override
    public Object clone()
    {
        return new APexpressionListLoop(
            cloneNode(this._tvirgula_),
            cloneNode(this._pexpression_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPexpressionListLoop(this);
    }

    public TTvirgula getTvirgula()
    {
        return this._tvirgula_;
    }

    public void setTvirgula(TTvirgula node)
    {
        if(this._tvirgula_ != null)
        {
            this._tvirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tvirgula_ = node;
    }

    public PPexpression getPexpression()
    {
        return this._pexpression_;
    }

    public void setPexpression(PPexpression node)
    {
        if(this._pexpression_ != null)
        {
            this._pexpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pexpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tvirgula_)
            + toString(this._pexpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tvirgula_ == child)
        {
            this._tvirgula_ = null;
            return;
        }

        if(this._pexpression_ == child)
        {
            this._pexpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tvirgula_ == oldChild)
        {
            setTvirgula((TTvirgula) newChild);
            return;
        }

        if(this._pexpression_ == oldChild)
        {
            setPexpression((PPexpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
