/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APfunctionDecl extends PPfunctionDecl
{
    private TTfunc _tfunc_;
    private PPfunctionName _pfunctionName_;
    private PPfunctionDeclAgrup _pfunctionDeclAgrup_;

    public APfunctionDecl()
    {
        // Constructor
    }

    public APfunctionDecl(
        @SuppressWarnings("hiding") TTfunc _tfunc_,
        @SuppressWarnings("hiding") PPfunctionName _pfunctionName_,
        @SuppressWarnings("hiding") PPfunctionDeclAgrup _pfunctionDeclAgrup_)
    {
        // Constructor
        setTfunc(_tfunc_);

        setPfunctionName(_pfunctionName_);

        setPfunctionDeclAgrup(_pfunctionDeclAgrup_);

    }

    @Override
    public Object clone()
    {
        return new APfunctionDecl(
            cloneNode(this._tfunc_),
            cloneNode(this._pfunctionName_),
            cloneNode(this._pfunctionDeclAgrup_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPfunctionDecl(this);
    }

    public TTfunc getTfunc()
    {
        return this._tfunc_;
    }

    public void setTfunc(TTfunc node)
    {
        if(this._tfunc_ != null)
        {
            this._tfunc_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tfunc_ = node;
    }

    public PPfunctionName getPfunctionName()
    {
        return this._pfunctionName_;
    }

    public void setPfunctionName(PPfunctionName node)
    {
        if(this._pfunctionName_ != null)
        {
            this._pfunctionName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pfunctionName_ = node;
    }

    public PPfunctionDeclAgrup getPfunctionDeclAgrup()
    {
        return this._pfunctionDeclAgrup_;
    }

    public void setPfunctionDeclAgrup(PPfunctionDeclAgrup node)
    {
        if(this._pfunctionDeclAgrup_ != null)
        {
            this._pfunctionDeclAgrup_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pfunctionDeclAgrup_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tfunc_)
            + toString(this._pfunctionName_)
            + toString(this._pfunctionDeclAgrup_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tfunc_ == child)
        {
            this._tfunc_ = null;
            return;
        }

        if(this._pfunctionName_ == child)
        {
            this._pfunctionName_ = null;
            return;
        }

        if(this._pfunctionDeclAgrup_ == child)
        {
            this._pfunctionDeclAgrup_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tfunc_ == oldChild)
        {
            setTfunc((TTfunc) newChild);
            return;
        }

        if(this._pfunctionName_ == oldChild)
        {
            setPfunctionName((PPfunctionName) newChild);
            return;
        }

        if(this._pfunctionDeclAgrup_ == oldChild)
        {
            setPfunctionDeclAgrup((PPfunctionDeclAgrup) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
