/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APfunctionPfunctionDeclAgrup extends PPfunctionDeclAgrup
{
    private PPfunction _pfunction_;

    public APfunctionPfunctionDeclAgrup()
    {
        // Constructor
    }

    public APfunctionPfunctionDeclAgrup(
        @SuppressWarnings("hiding") PPfunction _pfunction_)
    {
        // Constructor
        setPfunction(_pfunction_);

    }

    @Override
    public Object clone()
    {
        return new APfunctionPfunctionDeclAgrup(
            cloneNode(this._pfunction_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPfunctionPfunctionDeclAgrup(this);
    }

    public PPfunction getPfunction()
    {
        return this._pfunction_;
    }

    public void setPfunction(PPfunction node)
    {
        if(this._pfunction_ != null)
        {
            this._pfunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pfunction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pfunction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pfunction_ == child)
        {
            this._pfunction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pfunction_ == oldChild)
        {
            setPfunction((PPfunction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
