/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APidentifierListPidentifierList extends PPidentifierList
{
    private TTvirgula _tvirgula_;

    public APidentifierListPidentifierList()
    {
        // Constructor
    }

    public APidentifierListPidentifierList(
        @SuppressWarnings("hiding") TTvirgula _tvirgula_)
    {
        // Constructor
        setTvirgula(_tvirgula_);

    }

    @Override
    public Object clone()
    {
        return new APidentifierListPidentifierList(
            cloneNode(this._tvirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPidentifierListPidentifierList(this);
    }

    public TTvirgula getTvirgula()
    {
        return this._tvirgula_;
    }

    public void setTvirgula(TTvirgula node)
    {
        if(this._tvirgula_ != null)
        {
            this._tvirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tvirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tvirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tvirgula_ == child)
        {
            this._tvirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tvirgula_ == oldChild)
        {
            setTvirgula((TTvirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
