/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APifStmtOpc extends PPifStmtOpc
{
    private PPsimpleStmt _psimpleStmt_;
    private TTpontoEVirgula _tpontoEVirgula_;

    public APifStmtOpc()
    {
        // Constructor
    }

    public APifStmtOpc(
        @SuppressWarnings("hiding") PPsimpleStmt _psimpleStmt_,
        @SuppressWarnings("hiding") TTpontoEVirgula _tpontoEVirgula_)
    {
        // Constructor
        setPsimpleStmt(_psimpleStmt_);

        setTpontoEVirgula(_tpontoEVirgula_);

    }

    @Override
    public Object clone()
    {
        return new APifStmtOpc(
            cloneNode(this._psimpleStmt_),
            cloneNode(this._tpontoEVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPifStmtOpc(this);
    }

    public PPsimpleStmt getPsimpleStmt()
    {
        return this._psimpleStmt_;
    }

    public void setPsimpleStmt(PPsimpleStmt node)
    {
        if(this._psimpleStmt_ != null)
        {
            this._psimpleStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._psimpleStmt_ = node;
    }

    public TTpontoEVirgula getTpontoEVirgula()
    {
        return this._tpontoEVirgula_;
    }

    public void setTpontoEVirgula(TTpontoEVirgula node)
    {
        if(this._tpontoEVirgula_ != null)
        {
            this._tpontoEVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tpontoEVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._psimpleStmt_)
            + toString(this._tpontoEVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._psimpleStmt_ == child)
        {
            this._psimpleStmt_ = null;
            return;
        }

        if(this._tpontoEVirgula_ == child)
        {
            this._tpontoEVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._psimpleStmt_ == oldChild)
        {
            setPsimpleStmt((PPsimpleStmt) newChild);
            return;
        }

        if(this._tpontoEVirgula_ == oldChild)
        {
            setTpontoEVirgula((TTpontoEVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
