/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APindex extends PPindex
{
    private TTabreColchete _tabreColchete_;
    private PPexpression _pexpression_;
    private TTfechaColchete _tfechaColchete_;

    public APindex()
    {
        // Constructor
    }

    public APindex(
        @SuppressWarnings("hiding") TTabreColchete _tabreColchete_,
        @SuppressWarnings("hiding") PPexpression _pexpression_,
        @SuppressWarnings("hiding") TTfechaColchete _tfechaColchete_)
    {
        // Constructor
        setTabreColchete(_tabreColchete_);

        setPexpression(_pexpression_);

        setTfechaColchete(_tfechaColchete_);

    }

    @Override
    public Object clone()
    {
        return new APindex(
            cloneNode(this._tabreColchete_),
            cloneNode(this._pexpression_),
            cloneNode(this._tfechaColchete_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPindex(this);
    }

    public TTabreColchete getTabreColchete()
    {
        return this._tabreColchete_;
    }

    public void setTabreColchete(TTabreColchete node)
    {
        if(this._tabreColchete_ != null)
        {
            this._tabreColchete_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tabreColchete_ = node;
    }

    public PPexpression getPexpression()
    {
        return this._pexpression_;
    }

    public void setPexpression(PPexpression node)
    {
        if(this._pexpression_ != null)
        {
            this._pexpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pexpression_ = node;
    }

    public TTfechaColchete getTfechaColchete()
    {
        return this._tfechaColchete_;
    }

    public void setTfechaColchete(TTfechaColchete node)
    {
        if(this._tfechaColchete_ != null)
        {
            this._tfechaColchete_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tfechaColchete_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tabreColchete_)
            + toString(this._pexpression_)
            + toString(this._tfechaColchete_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tabreColchete_ == child)
        {
            this._tabreColchete_ = null;
            return;
        }

        if(this._pexpression_ == child)
        {
            this._pexpression_ = null;
            return;
        }

        if(this._tfechaColchete_ == child)
        {
            this._tfechaColchete_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tabreColchete_ == oldChild)
        {
            setTabreColchete((TTabreColchete) newChild);
            return;
        }

        if(this._pexpression_ == oldChild)
        {
            setPexpression((PPexpression) newChild);
            return;
        }

        if(this._tfechaColchete_ == oldChild)
        {
            setTfechaColchete((TTfechaColchete) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
