/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APliteralValueOpc extends PPliteralValueOpc
{
    private PPelementLit _pelementLit_;
    private TTvirgula _tvirgula_;

    public APliteralValueOpc()
    {
        // Constructor
    }

    public APliteralValueOpc(
        @SuppressWarnings("hiding") PPelementLit _pelementLit_,
        @SuppressWarnings("hiding") TTvirgula _tvirgula_)
    {
        // Constructor
        setPelementLit(_pelementLit_);

        setTvirgula(_tvirgula_);

    }

    @Override
    public Object clone()
    {
        return new APliteralValueOpc(
            cloneNode(this._pelementLit_),
            cloneNode(this._tvirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPliteralValueOpc(this);
    }

    public PPelementLit getPelementLit()
    {
        return this._pelementLit_;
    }

    public void setPelementLit(PPelementLit node)
    {
        if(this._pelementLit_ != null)
        {
            this._pelementLit_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pelementLit_ = node;
    }

    public TTvirgula getTvirgula()
    {
        return this._tvirgula_;
    }

    public void setTvirgula(TTvirgula node)
    {
        if(this._tvirgula_ != null)
        {
            this._tvirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tvirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pelementLit_)
            + toString(this._tvirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pelementLit_ == child)
        {
            this._pelementLit_ = null;
            return;
        }

        if(this._tvirgula_ == child)
        {
            this._tvirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pelementLit_ == oldChild)
        {
            setPelementLit((PPelementLit) newChild);
            return;
        }

        if(this._tvirgula_ == oldChild)
        {
            setTvirgula((TTvirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
