/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APmethodDeclPtopLevelDecl extends PPtopLevelDecl
{
    private PPmethodDecl _pmethodDecl_;

    public APmethodDeclPtopLevelDecl()
    {
        // Constructor
    }

    public APmethodDeclPtopLevelDecl(
        @SuppressWarnings("hiding") PPmethodDecl _pmethodDecl_)
    {
        // Constructor
        setPmethodDecl(_pmethodDecl_);

    }

    @Override
    public Object clone()
    {
        return new APmethodDeclPtopLevelDecl(
            cloneNode(this._pmethodDecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPmethodDeclPtopLevelDecl(this);
    }

    public PPmethodDecl getPmethodDecl()
    {
        return this._pmethodDecl_;
    }

    public void setPmethodDecl(PPmethodDecl node)
    {
        if(this._pmethodDecl_ != null)
        {
            this._pmethodDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pmethodDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pmethodDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pmethodDecl_ == child)
        {
            this._pmethodDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pmethodDecl_ == oldChild)
        {
            setPmethodDecl((PPmethodDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
