/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APparameterDecl extends PPparameterDecl
{
    private PPidentifierList _pidentifierList_;
    private PPtype _ptype_;

    public APparameterDecl()
    {
        // Constructor
    }

    public APparameterDecl(
        @SuppressWarnings("hiding") PPidentifierList _pidentifierList_,
        @SuppressWarnings("hiding") PPtype _ptype_)
    {
        // Constructor
        setPidentifierList(_pidentifierList_);

        setPtype(_ptype_);

    }

    @Override
    public Object clone()
    {
        return new APparameterDecl(
            cloneNode(this._pidentifierList_),
            cloneNode(this._ptype_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPparameterDecl(this);
    }

    public PPidentifierList getPidentifierList()
    {
        return this._pidentifierList_;
    }

    public void setPidentifierList(PPidentifierList node)
    {
        if(this._pidentifierList_ != null)
        {
            this._pidentifierList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pidentifierList_ = node;
    }

    public PPtype getPtype()
    {
        return this._ptype_;
    }

    public void setPtype(PPtype node)
    {
        if(this._ptype_ != null)
        {
            this._ptype_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ptype_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pidentifierList_)
            + toString(this._ptype_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pidentifierList_ == child)
        {
            this._pidentifierList_ = null;
            return;
        }

        if(this._ptype_ == child)
        {
            this._ptype_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pidentifierList_ == oldChild)
        {
            setPidentifierList((PPidentifierList) newChild);
            return;
        }

        if(this._ptype_ == oldChild)
        {
            setPtype((PPtype) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
