/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APpostStmt extends PPpostStmt
{
    private PPsimpleStmt _psimpleStmt_;

    public APpostStmt()
    {
        // Constructor
    }

    public APpostStmt(
        @SuppressWarnings("hiding") PPsimpleStmt _psimpleStmt_)
    {
        // Constructor
        setPsimpleStmt(_psimpleStmt_);

    }

    @Override
    public Object clone()
    {
        return new APpostStmt(
            cloneNode(this._psimpleStmt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPpostStmt(this);
    }

    public PPsimpleStmt getPsimpleStmt()
    {
        return this._psimpleStmt_;
    }

    public void setPsimpleStmt(PPsimpleStmt node)
    {
        if(this._psimpleStmt_ != null)
        {
            this._psimpleStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._psimpleStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._psimpleStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._psimpleStmt_ == child)
        {
            this._psimpleStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._psimpleStmt_ == oldChild)
        {
            setPsimpleStmt((PPsimpleStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
