/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APprogramLoop extends PPprogramLoop
{
    private PPtopLevelDecl _ptopLevelDecl_;
    private TTdelimitador _tdelimitador_;

    public APprogramLoop()
    {
        // Constructor
    }

    public APprogramLoop(
        @SuppressWarnings("hiding") PPtopLevelDecl _ptopLevelDecl_,
        @SuppressWarnings("hiding") TTdelimitador _tdelimitador_)
    {
        // Constructor
        setPtopLevelDecl(_ptopLevelDecl_);

        setTdelimitador(_tdelimitador_);

    }

    @Override
    public Object clone()
    {
        return new APprogramLoop(
            cloneNode(this._ptopLevelDecl_),
            cloneNode(this._tdelimitador_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPprogramLoop(this);
    }

    public PPtopLevelDecl getPtopLevelDecl()
    {
        return this._ptopLevelDecl_;
    }

    public void setPtopLevelDecl(PPtopLevelDecl node)
    {
        if(this._ptopLevelDecl_ != null)
        {
            this._ptopLevelDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ptopLevelDecl_ = node;
    }

    public TTdelimitador getTdelimitador()
    {
        return this._tdelimitador_;
    }

    public void setTdelimitador(TTdelimitador node)
    {
        if(this._tdelimitador_ != null)
        {
            this._tdelimitador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tdelimitador_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ptopLevelDecl_)
            + toString(this._tdelimitador_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ptopLevelDecl_ == child)
        {
            this._ptopLevelDecl_ = null;
            return;
        }

        if(this._tdelimitador_ == child)
        {
            this._tdelimitador_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ptopLevelDecl_ == oldChild)
        {
            setPtopLevelDecl((PPtopLevelDecl) newChild);
            return;
        }

        if(this._tdelimitador_ == oldChild)
        {
            setTdelimitador((TTdelimitador) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
