/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APprimaryExprPunaryExpr extends PPunaryExpr
{
    private PPprimaryExpr _pprimaryExpr_;

    public APprimaryExprPunaryExpr()
    {
        // Constructor
    }

    public APprimaryExprPunaryExpr(
        @SuppressWarnings("hiding") PPprimaryExpr _pprimaryExpr_)
    {
        // Constructor
        setPprimaryExpr(_pprimaryExpr_);

    }

    @Override
    public Object clone()
    {
        return new APprimaryExprPunaryExpr(
            cloneNode(this._pprimaryExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPprimaryExprPunaryExpr(this);
    }

    public PPprimaryExpr getPprimaryExpr()
    {
        return this._pprimaryExpr_;
    }

    public void setPprimaryExpr(PPprimaryExpr node)
    {
        if(this._pprimaryExpr_ != null)
        {
            this._pprimaryExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pprimaryExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pprimaryExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pprimaryExpr_ == child)
        {
            this._pprimaryExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pprimaryExpr_ == oldChild)
        {
            setPprimaryExpr((PPprimaryExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
