/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APsignaturePfunctionDeclAgrup extends PPfunctionDeclAgrup
{
    private PPsignature _psignature_;

    public APsignaturePfunctionDeclAgrup()
    {
        // Constructor
    }

    public APsignaturePfunctionDeclAgrup(
        @SuppressWarnings("hiding") PPsignature _psignature_)
    {
        // Constructor
        setPsignature(_psignature_);

    }

    @Override
    public Object clone()
    {
        return new APsignaturePfunctionDeclAgrup(
            cloneNode(this._psignature_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPsignaturePfunctionDeclAgrup(this);
    }

    public PPsignature getPsignature()
    {
        return this._psignature_;
    }

    public void setPsignature(PPsignature node)
    {
        if(this._psignature_ != null)
        {
            this._psignature_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._psignature_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._psignature_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._psignature_ == child)
        {
            this._psignature_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._psignature_ == oldChild)
        {
            setPsignature((PPsignature) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
