/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APstatementListLoop extends PPstatementListLoop
{
    private PPstatement _pstatement_;
    private TTpontoEVirgula _tpontoEVirgula_;

    public APstatementListLoop()
    {
        // Constructor
    }

    public APstatementListLoop(
        @SuppressWarnings("hiding") PPstatement _pstatement_,
        @SuppressWarnings("hiding") TTpontoEVirgula _tpontoEVirgula_)
    {
        // Constructor
        setPstatement(_pstatement_);

        setTpontoEVirgula(_tpontoEVirgula_);

    }

    @Override
    public Object clone()
    {
        return new APstatementListLoop(
            cloneNode(this._pstatement_),
            cloneNode(this._tpontoEVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPstatementListLoop(this);
    }

    public PPstatement getPstatement()
    {
        return this._pstatement_;
    }

    public void setPstatement(PPstatement node)
    {
        if(this._pstatement_ != null)
        {
            this._pstatement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pstatement_ = node;
    }

    public TTpontoEVirgula getTpontoEVirgula()
    {
        return this._tpontoEVirgula_;
    }

    public void setTpontoEVirgula(TTpontoEVirgula node)
    {
        if(this._tpontoEVirgula_ != null)
        {
            this._tpontoEVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tpontoEVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pstatement_)
            + toString(this._tpontoEVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pstatement_ == child)
        {
            this._pstatement_ = null;
            return;
        }

        if(this._tpontoEVirgula_ == child)
        {
            this._tpontoEVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pstatement_ == oldChild)
        {
            setPstatement((PPstatement) newChild);
            return;
        }

        if(this._tpontoEVirgula_ == oldChild)
        {
            setTpontoEVirgula((TTpontoEVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
