/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APtypePconstSpec2 extends PPconstSpec2
{
    private PPtype _ptype_;
    private TTigual _tigual_;
    private PPexpressionList _pexpressionList_;

    public APtypePconstSpec2()
    {
        // Constructor
    }

    public APtypePconstSpec2(
        @SuppressWarnings("hiding") PPtype _ptype_,
        @SuppressWarnings("hiding") TTigual _tigual_,
        @SuppressWarnings("hiding") PPexpressionList _pexpressionList_)
    {
        // Constructor
        setPtype(_ptype_);

        setTigual(_tigual_);

        setPexpressionList(_pexpressionList_);

    }

    @Override
    public Object clone()
    {
        return new APtypePconstSpec2(
            cloneNode(this._ptype_),
            cloneNode(this._tigual_),
            cloneNode(this._pexpressionList_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPtypePconstSpec2(this);
    }

    public PPtype getPtype()
    {
        return this._ptype_;
    }

    public void setPtype(PPtype node)
    {
        if(this._ptype_ != null)
        {
            this._ptype_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ptype_ = node;
    }

    public TTigual getTigual()
    {
        return this._tigual_;
    }

    public void setTigual(TTigual node)
    {
        if(this._tigual_ != null)
        {
            this._tigual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tigual_ = node;
    }

    public PPexpressionList getPexpressionList()
    {
        return this._pexpressionList_;
    }

    public void setPexpressionList(PPexpressionList node)
    {
        if(this._pexpressionList_ != null)
        {
            this._pexpressionList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pexpressionList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ptype_)
            + toString(this._tigual_)
            + toString(this._pexpressionList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ptype_ == child)
        {
            this._ptype_ = null;
            return;
        }

        if(this._tigual_ == child)
        {
            this._tigual_ = null;
            return;
        }

        if(this._pexpressionList_ == child)
        {
            this._pexpressionList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ptype_ == oldChild)
        {
            setPtype((PPtype) newChild);
            return;
        }

        if(this._tigual_ == oldChild)
        {
            setTigual((TTigual) newChild);
            return;
        }

        if(this._pexpressionList_ == oldChild)
        {
            setPexpressionList((PPexpressionList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
