/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APunaryExprPexpression extends PPexpression
{
    private PPunaryExpr _punaryExpr_;

    public APunaryExprPexpression()
    {
        // Constructor
    }

    public APunaryExprPexpression(
        @SuppressWarnings("hiding") PPunaryExpr _punaryExpr_)
    {
        // Constructor
        setPunaryExpr(_punaryExpr_);

    }

    @Override
    public Object clone()
    {
        return new APunaryExprPexpression(
            cloneNode(this._punaryExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPunaryExprPexpression(this);
    }

    public PPunaryExpr getPunaryExpr()
    {
        return this._punaryExpr_;
    }

    public void setPunaryExpr(PPunaryExpr node)
    {
        if(this._punaryExpr_ != null)
        {
            this._punaryExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._punaryExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._punaryExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._punaryExpr_ == child)
        {
            this._punaryExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._punaryExpr_ == oldChild)
        {
            setPunaryExpr((PPunaryExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
