/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APvarDeclAgrup extends PPvarDeclAgrup
{
    private TTabreParen _tabreParen_;
    private PPvarDeclAgrupParen _pvarDeclAgrupParen_;

    public APvarDeclAgrup()
    {
        // Constructor
    }

    public APvarDeclAgrup(
        @SuppressWarnings("hiding") TTabreParen _tabreParen_,
        @SuppressWarnings("hiding") PPvarDeclAgrupParen _pvarDeclAgrupParen_)
    {
        // Constructor
        setTabreParen(_tabreParen_);

        setPvarDeclAgrupParen(_pvarDeclAgrupParen_);

    }

    @Override
    public Object clone()
    {
        return new APvarDeclAgrup(
            cloneNode(this._tabreParen_),
            cloneNode(this._pvarDeclAgrupParen_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPvarDeclAgrup(this);
    }

    public TTabreParen getTabreParen()
    {
        return this._tabreParen_;
    }

    public void setTabreParen(TTabreParen node)
    {
        if(this._tabreParen_ != null)
        {
            this._tabreParen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tabreParen_ = node;
    }

    public PPvarDeclAgrupParen getPvarDeclAgrupParen()
    {
        return this._pvarDeclAgrupParen_;
    }

    public void setPvarDeclAgrupParen(PPvarDeclAgrupParen node)
    {
        if(this._pvarDeclAgrupParen_ != null)
        {
            this._pvarDeclAgrupParen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pvarDeclAgrupParen_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tabreParen_)
            + toString(this._pvarDeclAgrupParen_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tabreParen_ == child)
        {
            this._tabreParen_ = null;
            return;
        }

        if(this._pvarDeclAgrupParen_ == child)
        {
            this._pvarDeclAgrupParen_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tabreParen_ == oldChild)
        {
            setTabreParen((TTabreParen) newChild);
            return;
        }

        if(this._pvarDeclAgrupParen_ == oldChild)
        {
            setPvarDeclAgrupParen((PPvarDeclAgrupParen) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
