/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APvarDeclPdeclaration extends PPdeclaration
{
    private PPvarDecl _pvarDecl_;

    public APvarDeclPdeclaration()
    {
        // Constructor
    }

    public APvarDeclPdeclaration(
        @SuppressWarnings("hiding") PPvarDecl _pvarDecl_)
    {
        // Constructor
        setPvarDecl(_pvarDecl_);

    }

    @Override
    public Object clone()
    {
        return new APvarDeclPdeclaration(
            cloneNode(this._pvarDecl_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPvarDeclPdeclaration(this);
    }

    public PPvarDecl getPvarDecl()
    {
        return this._pvarDecl_;
    }

    public void setPvarDecl(PPvarDecl node)
    {
        if(this._pvarDecl_ != null)
        {
            this._pvarDecl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pvarDecl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pvarDecl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pvarDecl_ == child)
        {
            this._pvarDecl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pvarDecl_ == oldChild)
        {
            setPvarDecl((PPvarDecl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
