/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ATabreColchetePliteralType extends PPliteralType
{
    private TTabreColchete _tabreColchete_;
    private TTellipsis _tellipsis_;
    private TTfechaColchete _tfechaColchete_;
    private PPelementType _pelementType_;

    public ATabreColchetePliteralType()
    {
        // Constructor
    }

    public ATabreColchetePliteralType(
        @SuppressWarnings("hiding") TTabreColchete _tabreColchete_,
        @SuppressWarnings("hiding") TTellipsis _tellipsis_,
        @SuppressWarnings("hiding") TTfechaColchete _tfechaColchete_,
        @SuppressWarnings("hiding") PPelementType _pelementType_)
    {
        // Constructor
        setTabreColchete(_tabreColchete_);

        setTellipsis(_tellipsis_);

        setTfechaColchete(_tfechaColchete_);

        setPelementType(_pelementType_);

    }

    @Override
    public Object clone()
    {
        return new ATabreColchetePliteralType(
            cloneNode(this._tabreColchete_),
            cloneNode(this._tellipsis_),
            cloneNode(this._tfechaColchete_),
            cloneNode(this._pelementType_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATabreColchetePliteralType(this);
    }

    public TTabreColchete getTabreColchete()
    {
        return this._tabreColchete_;
    }

    public void setTabreColchete(TTabreColchete node)
    {
        if(this._tabreColchete_ != null)
        {
            this._tabreColchete_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tabreColchete_ = node;
    }

    public TTellipsis getTellipsis()
    {
        return this._tellipsis_;
    }

    public void setTellipsis(TTellipsis node)
    {
        if(this._tellipsis_ != null)
        {
            this._tellipsis_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tellipsis_ = node;
    }

    public TTfechaColchete getTfechaColchete()
    {
        return this._tfechaColchete_;
    }

    public void setTfechaColchete(TTfechaColchete node)
    {
        if(this._tfechaColchete_ != null)
        {
            this._tfechaColchete_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tfechaColchete_ = node;
    }

    public PPelementType getPelementType()
    {
        return this._pelementType_;
    }

    public void setPelementType(PPelementType node)
    {
        if(this._pelementType_ != null)
        {
            this._pelementType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pelementType_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tabreColchete_)
            + toString(this._tellipsis_)
            + toString(this._tfechaColchete_)
            + toString(this._pelementType_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tabreColchete_ == child)
        {
            this._tabreColchete_ = null;
            return;
        }

        if(this._tellipsis_ == child)
        {
            this._tellipsis_ = null;
            return;
        }

        if(this._tfechaColchete_ == child)
        {
            this._tfechaColchete_ = null;
            return;
        }

        if(this._pelementType_ == child)
        {
            this._pelementType_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tabreColchete_ == oldChild)
        {
            setTabreColchete((TTabreColchete) newChild);
            return;
        }

        if(this._tellipsis_ == oldChild)
        {
            setTellipsis((TTellipsis) newChild);
            return;
        }

        if(this._tfechaColchete_ == oldChild)
        {
            setTfechaColchete((TTfechaColchete) newChild);
            return;
        }

        if(this._pelementType_ == oldChild)
        {
            setPelementType((PPelementType) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
