/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ATadicaoPunaryOp extends PPunaryOp
{
    private TTadicao _tadicao_;

    public ATadicaoPunaryOp()
    {
        // Constructor
    }

    public ATadicaoPunaryOp(
        @SuppressWarnings("hiding") TTadicao _tadicao_)
    {
        // Constructor
        setTadicao(_tadicao_);

    }

    @Override
    public Object clone()
    {
        return new ATadicaoPunaryOp(
            cloneNode(this._tadicao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATadicaoPunaryOp(this);
    }

    public TTadicao getTadicao()
    {
        return this._tadicao_;
    }

    public void setTadicao(TTadicao node)
    {
        if(this._tadicao_ != null)
        {
            this._tadicao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tadicao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tadicao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tadicao_ == child)
        {
            this._tadicao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tadicao_ == oldChild)
        {
            setTadicao((TTadicao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
