/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ATbarraPmulOp extends PPmulOp
{
    private TTbarra _tbarra_;

    public ATbarraPmulOp()
    {
        // Constructor
    }

    public ATbarraPmulOp(
        @SuppressWarnings("hiding") TTbarra _tbarra_)
    {
        // Constructor
        setTbarra(_tbarra_);

    }

    @Override
    public Object clone()
    {
        return new ATbarraPmulOp(
            cloneNode(this._tbarra_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATbarraPmulOp(this);
    }

    public TTbarra getTbarra()
    {
        return this._tbarra_;
    }

    public void setTbarra(TTbarra node)
    {
        if(this._tbarra_ != null)
        {
            this._tbarra_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tbarra_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tbarra_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tbarra_ == child)
        {
            this._tbarra_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tbarra_ == oldChild)
        {
            setTbarra((TTbarra) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
