/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ATidentifierPbinaryRelTermo extends PPbinaryRelTermo
{
    private TTidentifier _tidentifier_;

    public ATidentifierPbinaryRelTermo()
    {
        // Constructor
    }

    public ATidentifierPbinaryRelTermo(
        @SuppressWarnings("hiding") TTidentifier _tidentifier_)
    {
        // Constructor
        setTidentifier(_tidentifier_);

    }

    @Override
    public Object clone()
    {
        return new ATidentifierPbinaryRelTermo(
            cloneNode(this._tidentifier_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATidentifierPbinaryRelTermo(this);
    }

    public TTidentifier getTidentifier()
    {
        return this._tidentifier_;
    }

    public void setTidentifier(TTidentifier node)
    {
        if(this._tidentifier_ != null)
        {
            this._tidentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tidentifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tidentifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tidentifier_ == child)
        {
            this._tidentifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tidentifier_ == oldChild)
        {
            setTidentifier((TTidentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
