/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ATigualIgualPrelOp extends PPrelOp
{
    private TTigualIgual _tigualIgual_;

    public ATigualIgualPrelOp()
    {
        // Constructor
    }

    public ATigualIgualPrelOp(
        @SuppressWarnings("hiding") TTigualIgual _tigualIgual_)
    {
        // Constructor
        setTigualIgual(_tigualIgual_);

    }

    @Override
    public Object clone()
    {
        return new ATigualIgualPrelOp(
            cloneNode(this._tigualIgual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATigualIgualPrelOp(this);
    }

    public TTigualIgual getTigualIgual()
    {
        return this._tigualIgual_;
    }

    public void setTigualIgual(TTigualIgual node)
    {
        if(this._tigualIgual_ != null)
        {
            this._tigualIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tigualIgual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tigualIgual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tigualIgual_ == child)
        {
            this._tigualIgual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tigualIgual_ == oldChild)
        {
            setTigualIgual((TTigualIgual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
