/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ATmaiorPrelOp extends PPrelOp
{
    private TTmaior _tmaior_;

    public ATmaiorPrelOp()
    {
        // Constructor
    }

    public ATmaiorPrelOp(
        @SuppressWarnings("hiding") TTmaior _tmaior_)
    {
        // Constructor
        setTmaior(_tmaior_);

    }

    @Override
    public Object clone()
    {
        return new ATmaiorPrelOp(
            cloneNode(this._tmaior_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATmaiorPrelOp(this);
    }

    public TTmaior getTmaior()
    {
        return this._tmaior_;
    }

    public void setTmaior(TTmaior node)
    {
        if(this._tmaior_ != null)
        {
            this._tmaior_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tmaior_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tmaior_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tmaior_ == child)
        {
            this._tmaior_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tmaior_ == oldChild)
        {
            setTmaior((TTmaior) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
