/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ATmenorPrelOp extends PPrelOp
{
    private TTmenor _tmenor_;

    public ATmenorPrelOp()
    {
        // Constructor
    }

    public ATmenorPrelOp(
        @SuppressWarnings("hiding") TTmenor _tmenor_)
    {
        // Constructor
        setTmenor(_tmenor_);

    }

    @Override
    public Object clone()
    {
        return new ATmenorPrelOp(
            cloneNode(this._tmenor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATmenorPrelOp(this);
    }

    public TTmenor getTmenor()
    {
        return this._tmenor_;
    }

    public void setTmenor(TTmenor node)
    {
        if(this._tmenor_ != null)
        {
            this._tmenor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tmenor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tmenor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tmenor_ == child)
        {
            this._tmenor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tmenor_ == oldChild)
        {
            setTmenor((TTmenor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
