/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ATsubtracaoPunaryOp extends PPunaryOp
{
    private TTsubtracao _tsubtracao_;

    public ATsubtracaoPunaryOp()
    {
        // Constructor
    }

    public ATsubtracaoPunaryOp(
        @SuppressWarnings("hiding") TTsubtracao _tsubtracao_)
    {
        // Constructor
        setTsubtracao(_tsubtracao_);

    }

    @Override
    public Object clone()
    {
        return new ATsubtracaoPunaryOp(
            cloneNode(this._tsubtracao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATsubtracaoPunaryOp(this);
    }

    public TTsubtracao getTsubtracao()
    {
        return this._tsubtracao_;
    }

    public void setTsubtracao(TTsubtracao node)
    {
        if(this._tsubtracao_ != null)
        {
            this._tsubtracao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tsubtracao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tsubtracao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tsubtracao_ == child)
        {
            this._tsubtracao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tsubtracao_ == oldChild)
        {
            setTsubtracao((TTsubtracao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
