/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class TDeclaracaoAtribuicao extends Token
{
    public TDeclaracaoAtribuicao()
    {
        super.setText(":=");
    }

    public TDeclaracaoAtribuicao(int line, int pos)
    {
        super.setText(":=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDeclaracaoAtribuicao(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDeclaracaoAtribuicao(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDeclaracaoAtribuicao text.");
    }
}
