/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class TTdefer extends Token
{
    public TTdefer()
    {
        super.setText("defer");
    }

    public TTdefer(int line, int pos)
    {
        super.setText("defer");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTdefer(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTdefer(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTdefer text.");
    }
}
