/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class TTint64 extends Token
{
    public TTint64()
    {
        super.setText("int64");
    }

    public TTint64(int line, int pos)
    {
        super.setText("int64");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTint64(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTint64(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTint64 text.");
    }
}
