/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class TTrange extends Token
{
    public TTrange()
    {
        super.setText("range");
    }

    public TTrange(int line, int pos)
    {
        super.setText("range");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTrange(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTrange(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTrange text.");
    }
}
