/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.parser;

import compilador.node.*;
import compilador.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTTnumero(@SuppressWarnings("unused") TTnumero node)
    {
        this.index = 0;
    }

    @Override
    public void caseTTnumerooctal(@SuppressWarnings("unused") TTnumerooctal node)
    {
        this.index = 1;
    }

    @Override
    public void caseTTnumerohexa(@SuppressWarnings("unused") TTnumerohexa node)
    {
        this.index = 2;
    }

    @Override
    public void caseTTcomentBloco(@SuppressWarnings("unused") TTcomentBloco node)
    {
        this.index = 3;
    }

    @Override
    public void caseTTnomePrograma(@SuppressWarnings("unused") TTnomePrograma node)
    {
        this.index = 4;
    }

    @Override
    public void caseTTstring(@SuppressWarnings("unused") TTstring node)
    {
        this.index = 5;
    }

    @Override
    public void caseTTespaco(@SuppressWarnings("unused") TTespaco node)
    {
        this.index = 6;
    }

    @Override
    public void caseTTquebra(@SuppressWarnings("unused") TTquebra node)
    {
        this.index = 7;
    }

    @Override
    public void caseTTidentacao(@SuppressWarnings("unused") TTidentacao node)
    {
        this.index = 8;
    }

    @Override
    public void caseTTadicao(@SuppressWarnings("unused") TTadicao node)
    {
        this.index = 9;
    }

    @Override
    public void caseTTsubtracao(@SuppressWarnings("unused") TTsubtracao node)
    {
        this.index = 10;
    }

    @Override
    public void caseTTbarra(@SuppressWarnings("unused") TTbarra node)
    {
        this.index = 11;
    }

    @Override
    public void caseTTestrela(@SuppressWarnings("unused") TTestrela node)
    {
        this.index = 12;
    }

    @Override
    public void caseTTmenor(@SuppressWarnings("unused") TTmenor node)
    {
        this.index = 13;
    }

    @Override
    public void caseTTmenorIgual(@SuppressWarnings("unused") TTmenorIgual node)
    {
        this.index = 14;
    }

    @Override
    public void caseTTmaior(@SuppressWarnings("unused") TTmaior node)
    {
        this.index = 15;
    }

    @Override
    public void caseTTmaiorIgual(@SuppressWarnings("unused") TTmaiorIgual node)
    {
        this.index = 16;
    }

    @Override
    public void caseTTseta(@SuppressWarnings("unused") TTseta node)
    {
        this.index = 17;
    }

    @Override
    public void caseTTigualIgual(@SuppressWarnings("unused") TTigualIgual node)
    {
        this.index = 18;
    }

    @Override
    public void caseTTdiferente(@SuppressWarnings("unused") TTdiferente node)
    {
        this.index = 19;
    }

    @Override
    public void caseTTigual(@SuppressWarnings("unused") TTigual node)
    {
        this.index = 20;
    }

    @Override
    public void caseTTpontoEVirgula(@SuppressWarnings("unused") TTpontoEVirgula node)
    {
        this.index = 21;
    }

    @Override
    public void caseTTdelimitador(@SuppressWarnings("unused") TTdelimitador node)
    {
        this.index = 22;
    }

    @Override
    public void caseTTvirgula(@SuppressWarnings("unused") TTvirgula node)
    {
        this.index = 23;
    }

    @Override
    public void caseTTabreParen(@SuppressWarnings("unused") TTabreParen node)
    {
        this.index = 24;
    }

    @Override
    public void caseTTfechaParen(@SuppressWarnings("unused") TTfechaParen node)
    {
        this.index = 25;
    }

    @Override
    public void caseTTabreColchete(@SuppressWarnings("unused") TTabreColchete node)
    {
        this.index = 26;
    }

    @Override
    public void caseTTfechaColchete(@SuppressWarnings("unused") TTfechaColchete node)
    {
        this.index = 27;
    }

    @Override
    public void caseTTabreChave(@SuppressWarnings("unused") TTabreChave node)
    {
        this.index = 28;
    }

    @Override
    public void caseTTfechaChave(@SuppressWarnings("unused") TTfechaChave node)
    {
        this.index = 29;
    }

    @Override
    public void caseTTabreComent(@SuppressWarnings("unused") TTabreComent node)
    {
        this.index = 30;
    }

    @Override
    public void caseTTfechaComent(@SuppressWarnings("unused") TTfechaComent node)
    {
        this.index = 31;
    }

    @Override
    public void caseTTponto(@SuppressWarnings("unused") TTponto node)
    {
        this.index = 32;
    }

    @Override
    public void caseTTdoispontos(@SuppressWarnings("unused") TTdoispontos node)
    {
        this.index = 33;
    }

    @Override
    public void caseTTandLogico(@SuppressWarnings("unused") TTandLogico node)
    {
        this.index = 34;
    }

    @Override
    public void caseTTorLogico(@SuppressWarnings("unused") TTorLogico node)
    {
        this.index = 35;
    }

    @Override
    public void caseTTnotLogico(@SuppressWarnings("unused") TTnotLogico node)
    {
        this.index = 36;
    }

    @Override
    public void caseTTdeclaracaoAtribuicao(@SuppressWarnings("unused") TTdeclaracaoAtribuicao node)
    {
        this.index = 37;
    }

    @Override
    public void caseTTellipsis(@SuppressWarnings("unused") TTellipsis node)
    {
        this.index = 38;
    }

    @Override
    public void caseTTdefault(@SuppressWarnings("unused") TTdefault node)
    {
        this.index = 39;
    }

    @Override
    public void caseTTcase(@SuppressWarnings("unused") TTcase node)
    {
        this.index = 40;
    }

    @Override
    public void caseTTif(@SuppressWarnings("unused") TTif node)
    {
        this.index = 41;
    }

    @Override
    public void caseTTelse(@SuppressWarnings("unused") TTelse node)
    {
        this.index = 42;
    }

    @Override
    public void caseTTfunc(@SuppressWarnings("unused") TTfunc node)
    {
        this.index = 43;
    }

    @Override
    public void caseTTdefer(@SuppressWarnings("unused") TTdefer node)
    {
        this.index = 44;
    }

    @Override
    public void caseTTreturn(@SuppressWarnings("unused") TTreturn node)
    {
        this.index = 45;
    }

    @Override
    public void caseTTrange(@SuppressWarnings("unused") TTrange node)
    {
        this.index = 46;
    }

    @Override
    public void caseTTfor(@SuppressWarnings("unused") TTfor node)
    {
        this.index = 47;
    }

    @Override
    public void caseTTvar(@SuppressWarnings("unused") TTvar node)
    {
        this.index = 48;
    }

    @Override
    public void caseTTconst(@SuppressWarnings("unused") TTconst node)
    {
        this.index = 49;
    }

    @Override
    public void caseTTbool(@SuppressWarnings("unused") TTbool node)
    {
        this.index = 50;
    }

    @Override
    public void caseTTint32(@SuppressWarnings("unused") TTint32 node)
    {
        this.index = 51;
    }

    @Override
    public void caseTTint64(@SuppressWarnings("unused") TTint64 node)
    {
        this.index = 52;
    }

    @Override
    public void caseTTtipo(@SuppressWarnings("unused") TTtipo node)
    {
        this.index = 53;
    }

    @Override
    public void caseTTidentifier(@SuppressWarnings("unused") TTidentifier node)
    {
        this.index = 54;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 55;
    }
}
